# Generated by Django 5.1.3 on 2025-01-05 17:57

import api.models.user
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="category id"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="category name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="category description"
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="payment method id",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="payment method icon",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="payment method name"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=255, verbose_name="payment method value"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="payment method description"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active status"),
                ),
            ],
            options={
                "verbose_name": "payment method",
                "verbose_name_plural": "payment methods",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="product id",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="product name")),
                ("description", models.TextField(verbose_name="product description")),
                (
                    "summary",
                    models.TextField(
                        blank=True, null=True, verbose_name="product summary"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="product rating",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="product attribute id",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        max_length=255, verbose_name="product attribute type"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=255, verbose_name="product attribute value"
                    ),
                ),
            ],
            options={
                "verbose_name": "product attribute",
                "verbose_name_plural": "product attributes",
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "code",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="province code"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="province name"),
                ),
                (
                    "division_type",
                    models.CharField(max_length=255, verbose_name="province type"),
                ),
                (
                    "codename",
                    models.CharField(max_length=255, verbose_name="province codename"),
                ),
                ("phone_code", models.IntegerField(verbose_name="province phone code")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active status"),
                ),
            ],
            options={
                "verbose_name": "province",
                "verbose_name_plural": "provinces",
            },
        ),
        migrations.CreateModel(
            name="ShipmentMethod",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="shipment method id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="shipment method name"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=255, verbose_name="shipment method value"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="shipment method description",
                    ),
                ),
                (
                    "estimated_shipping_days",
                    models.IntegerField(verbose_name="estimated shipping days"),
                ),
                ("shipping_fee", models.FloatField(verbose_name="shipping fee")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active status"),
                ),
            ],
            options={
                "verbose_name": "shipment method",
                "verbose_name_plural": "shipment methods",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="user id",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="user avatar"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email adress"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="username"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="password"
                    ),
                ),
                (
                    "birth_of_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="birth of date"
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="telephone number",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
            managers=[
                ("objects", api.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="address id"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="address title",
                    ),
                ),
                ("city", models.CharField(max_length=255, verbose_name="city")),
                ("district", models.CharField(max_length=255, verbose_name="district")),
                ("ward", models.CharField(max_length=255, verbose_name="ward")),
                (
                    "address_1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address 1"
                    ),
                ),
                (
                    "address_2",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="address 2"
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="telephone number"
                    ),
                ),
                (
                    "representative",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="representative"
                    ),
                ),
                (
                    "display_address1",
                    models.CharField(max_length=255, verbose_name="display address"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="is default address"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="cart id",
                    ),
                ),
                (
                    "total_quantity",
                    models.IntegerField(default=0, verbose_name="total quantity"),
                ),
                (
                    "total_amount",
                    models.FloatField(default=0, verbose_name="total amount"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "cart",
                "verbose_name_plural": "carts",
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="order id",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("shipping", "Shipping"),
                            ("delivered", "Delivered"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=255,
                        verbose_name="order status",
                    ),
                ),
                ("total_quantity", models.IntegerField(verbose_name="total quantity")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "order detail",
                "verbose_name_plural": "order details",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="payment id",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("fail", "Fail"),
                            ("refund", "Refund"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="payment status",
                    ),
                ),
                ("total_amount", models.FloatField(verbose_name="total amount")),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="api.orderdetail",
                        verbose_name="order",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.paymentmethod",
                        verbose_name="payment_method",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
            },
        ),
        migrations.CreateModel(
            name="ProductSku",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="product id",
                    ),
                ),
                ("sku", models.CharField(max_length=255, verbose_name="product sku")),
                ("price", models.FloatField(verbose_name="product price")),
                ("quantity", models.IntegerField(verbose_name="product quantity")),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_color",
                        to="api.productattribute",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skus",
                        to="api.product",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_size",
                        to="api.productattribute",
                    ),
                ),
            ],
            options={
                "verbose_name": "product sku",
                "verbose_name_plural": "product skus",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="product image id",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="product image",
                    ),
                ),
                (
                    "feature",
                    models.TextField(
                        blank=True, null=True, verbose_name="product feature"
                    ),
                ),
                (
                    "product_sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="api.productsku",
                    ),
                ),
            ],
            options={
                "verbose_name": "product image",
                "verbose_name_plural": "product images",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="order item id",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="product quantity")),
                ("subtotal", models.FloatField(default=0, verbose_name="subtotal")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.orderdetail",
                    ),
                ),
                (
                    "product_sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.productsku"
                    ),
                ),
            ],
            options={
                "verbose_name": "order item",
                "verbose_name_plural": "order items",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="cart item id"
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="product quantity")),
                ("subtotal", models.FloatField(default=0, verbose_name="subtotal")),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.cart"
                    ),
                ),
                (
                    "product_sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.productsku"
                    ),
                ),
            ],
            options={
                "verbose_name": "cart item",
                "verbose_name_plural": "cart items",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "code",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="district code"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="district name"),
                ),
                (
                    "division_type",
                    models.CharField(max_length=255, verbose_name="district type"),
                ),
                (
                    "codename",
                    models.CharField(max_length=255, verbose_name="district codename"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active status"),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="api.province",
                        verbose_name="province",
                    ),
                ),
            ],
            options={
                "verbose_name": "district",
                "verbose_name_plural": "districts",
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="shipment id"
                    ),
                ),
                ("shipping_date", models.DateTimeField()),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="api.orderdetail",
                        verbose_name="order",
                    ),
                ),
                (
                    "receive_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.address"
                    ),
                ),
                (
                    "shipment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.shipmentmethod",
                        verbose_name="shipment_method",
                    ),
                ),
            ],
            options={
                "verbose_name": "shipment",
                "verbose_name_plural": "shipments",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="subcategory id"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="subcategory name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="subcategory description"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.category",
                        verbose_name="parent category",
                    ),
                ),
            ],
            options={
                "verbose_name": "subcategory",
                "verbose_name_plural": "subcategories",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                to="api.subcategory", verbose_name="product categories"
            ),
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "code",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ward code"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ward name")),
                (
                    "division_type",
                    models.CharField(max_length=255, verbose_name="ward type"),
                ),
                (
                    "codename",
                    models.CharField(max_length=255, verbose_name="ward codename"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active status"),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wards",
                        to="api.district",
                        verbose_name="district",
                    ),
                ),
            ],
            options={
                "verbose_name": "ward",
                "verbose_name_plural": "wards",
            },
        ),
        migrations.CreateModel(
            name="WishList",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="wishList id"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "wishlist",
                "verbose_name_plural": "wishlists",
            },
        ),
    ]
